# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0005_review_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='light.User'),
        ),
    ]
