# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0006_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='topic',
            field=models.CharField(default='Venue', max_length=255),
            preserve_default=False,
        ),
    ]
