# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0007_review_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.CharField(default='Strummers', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(default='Kendrick Lamar', max_length=255),
            preserve_default=False,
        ),
    ]
