# Generated by Django 2.0.1 on 2018-01-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0009_auto_20180105_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='json',
        ),
    ]
